name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t decal-applier:latest .

      - name: Deploy
        run: |
          docker stop decal-applier || true
          docker rm decal-applier || true
          docker run -d \
            --name decal-applier \
            --restart unless-stopped \
            --network web \
            --env-file /home/ljtijhuis/services/decal-applier/.env \
            -p 3001:3001 \
            decal-applier:latest